openapi: 3.0.3
info:
  title: Brain.Academy
  description: This is API for Group Project By Alterra Academy
  version: "1.0.0"
  contact:
    email: alfianadityadwi@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ALFIANADSAPUTRA_1/DashboardQ/1.0.0
  # Main URL
  - description: Main URL
    url: URL will be update soon
tags:
  - name: login
    description: endpoint for verifying who a user is
  - name: admin
  - name: user
  - name: mentee
  - name: class
  - name: feedback

paths:
  /login:
    post:
      tags:
        - "login"
      summary: "login account"
      description: "feature for verifying who a admin or user is"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
            example:
              email: "alfian@example.com"
              password: "alifganteng"
      responses:
        200:
          description: "login"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                data:
                  id: 6
                  full_name: "alfian aditya"
                  email: "alfian@example.com"
                  gender: "Male"
                  role: "User"
                  team: "Academy"
                  phone: "0812334455"
                  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VySUQiOjR9.QTZxERh4CwC_UnL_eJvTi_A_qdLeBZ-IjR4nqoxjodk"
                message: "login success"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"

  /users:
    post:
      tags:
        - "admin"
      summary: "register new user"
      description: "feature for admin register new user"
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                birth_date:
                  type: string
                gender:
                  type: string
                address:
                  type: string
                role:
                  type: string
                team:
                  type: string
                status:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                  format: password
            example:
              name: "alfian aditya"
              email: "alfian@example.com"
              birth_date: "2020-02-20"
              gender: "male"
              address: "jln. Merpati No 18, Kasihan, Bantul, Yogyakarta, 55184"
              role: "User"
              team: "Academy"
              status: "Active"
              phone: "0812334455"
              password: "alifganteng"
      responses:
        201:
          description: "insert user data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                message: "success create user account"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"

    get:
      tags:
        - "user"
      summary: "get all user data"
      description: "feature add all users data"
      security:
        - JWTAuth: []
      parameters:
        - name: name
          description: "user name"
          required: false
          in: query
          schema:
            type: string
            example: "Ahmad Zaori"
        - name: email
          description: "user email"
          required: false
          in: query
          schema:
            type: string
            example: "ahzoi@example.com"
        - name: team
          description: "user team"
          required: false
          in: query
          schema:
            type: string
            example: "Mentor"
        - name: role
          description: "user role"
          required: false
          in: query
          schema:
            type: string
            example: "User"
        - name: status
          description: "user status"
          required: false
          in: query
          schema:
            type: string
            example: "Active"
        - name: limit
          description: "limit"
          required: false
          in: query
          schema:
            type: integer
            example: 10
        - name: offset
          description: "offset"
          required: false
          in: query
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: "show users data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObjectArr"
              example:
                data:
                  - id: 2
                    name: "Azura Namini"
                    email: "azure@example.com"
                    team: "Admission"
                    role: "User"
                    status: "Active"
                  - id: 3
                    name: "Muhammad Arnold"
                    email: "marnold@example.com"
                    team: "Placement"
                    role: "User"
                    status: "Active"
                  - id: 4
                    name: "Beni Kurnia"
                    email: "benkur@example.com"
                    team: "Mentor"
                    role: "User"
                    status: "Active"
                  - id: 5
                    name: "Miranda Ramadhan"
                    email: "miranda@example.com"
                    team: "Placement"
                    role: "User"
                    status: "Non-Active"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"

  /users/{id}:
    put:
      tags:
        - "user"
      summary: "edit user profile"
      description: "feature for edit user profile"
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              name: "Azura Namini"
              email: "azure@example.com"
              team: "Placement"
              role: "User"
              status: "Active"
      responses:
        200:
          description: "update profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                data:
                  id: 2
                  name: "Azura Namini"
                  email: "azure@example.com"
                  team: "Placement"
                  role: "User"
                  status: "Active"
                message: "success update profile"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
    get:
      tags:
        - "user"
      summary: "show user profile by id"
      description: "feature for edit user profile"
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "show user profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                data:
                  id: 6
                  name: "alfian aditya"
                  email: "alfian@example.com"
                  birth_date: "2020-02-20"
                  gender: "male"
                  address: "Bantul, Yogyakarta, 55184"
                  role: "User"
                  team: "Academy"
                  status: "Active"
                  phone: "0812334455"
                message: "success show profile"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
    delete:
      tags:
        - "user"
      summary: "deactive user account"
      description: "feature for deactive user account"
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "deactive user account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                message: "success deactive user account"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"

  /mentee:
    post:
      tags:
        - "mentee"
      summary: "add mentee by admin"
      description: "feature for add mentee from admin side"
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                birth_date:
                  type: string
                address:
                  type: string
                gender:
                  type: string
                telegram:
                  type: string
                phone:
                  type: string
                class:
                  type: string
                status:
                  type: string
                category:
                  type: string
            example:
              name: "Susilo Ahmad"
              email: "susiloahmd@example.com"
              birth_date: "1995-12-03"
              address: "Ubud, Bali"
              gender: "Male"
              telegram: "08211223344"
              phone: "08211223344"
              class: "BE Batch 10"
              status: "Active"
              category: "Non-IT"
      responses:
        201:
          description: "add mentee data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                message: "success create mentee"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"

    get:
      tags:
        - "mentee"
      summary: "show all mentee"
      description: "feature for show all mentee data by admin"
      security:
        - JWTAuth: []
      parameters:
        - name: name
          description: "mentee name"
          required: false
          in: query
          schema:
            type: string
            example: "Alfian Aditya"
        - name: class
          description: "mentee class"
          required: false
          in: query
          schema:
            type: string
            example: "BE 15"
        - name: status
          description: "mentee status"
          required: false
          in: query
          schema:
            type: string
            example: "Active"
        - name: gender
          description: "mentee gender"
          required: false
          in: query
          schema:
            type: string
            example: "Male"
        - name: limit
          description: "limit"
          required: false
          in: query
          schema:
            type: integer
            example: 10
        - name: offset
          description: "offset"
          required: false
          in: query
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: "show all mentee data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObjectArr"
              example:
                data:
                  - id: 1
                    name: "Susilo Ahmad"
                    class: "BE 10"
                    status: "Active"
                    category: "Non-IT"
                    gender: "Male"
                  - id: 2
                    name: "Gigih Prakosa"
                    class:  "BE Batch 9"
                    status: "Active"
                    category: "IT"
                    gender: "Male"
                  - id: 3
                    name: "Veronica Ayu"
                    class: "FE Batch 9"
                    status: "Garduated"
                    category:  "IT"
                    gender: "Female"
                  - id: 4
                    name: "Nabila Hanifa"
                    class:  "FE 8"
                    status: "Gradueted"
                    category: "Non-IT"
                    gender: "Female"
                  - id: 5
                    name: "Akbar Rasyid"
                    class: "QE Batch 10"
                    status: "Eliminated"
                    category: "Non-IT"
                    gender: "Male"
                message: "success show all mentee"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"

  /mentee/{id}:
    get:
      tags:
        - "mentee"
      summary: "show mentee profile by id"
      description: "feature for show mentee profile by id"
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "show mentee profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                data:
                  id: 1
                  name: "Susilo Ahmad"
                  email: "susiloahmd@example.com"
                  birth_date: "1995-12-03"
                  address: "Ubud, Bali"
                  gender: "Male"
                  telegram: "08211223344"
                  phone: "08211223344"
                  class: "BE Batch 10"
                  status: "Active"
                  category: "Non-IT"
                message: "success show mentee profile"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
    put:
      tags:
        - "mentee"
      summary: "edit mentee profile"
      description: "feature for edit mentee data by id"
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              name: "Susilo Ahmad"
              email: "susiloahmd@example.com"
              birth_date: "1995-12-03"
              address: "Ubud, Bali"
              gender: "Male"
              telegram: "08211223344"
              phone: "08211223344"
              class: "BE Batch 10"
              status: "Graduated"
              category: "Non-IT"
      responses:
        200:
          description: "update mentee data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                data:
                  id: 1
                  name: "Susilo Ahmad"
                  email: "susiloahmd@example.com"
                  birth_date: "1995-12-03"
                  address: "Ubud, Bali"
                  gender: "Male"
                  telegram: "08211223344"
                  phone: "08211223344"
                  class: "BE Batch 10"
                  status: "Graduated"
                  category: "Non-IT"
                message: "success update mentee data"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
    delete:
      tags:
        - "mentee"
      summary: "delete mentee data"
      description: "feature for delete mentee data"
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "delete mentee data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                message: "success delete mentee data"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
      
components:
  schemas:
    responseObject:
      type: object
      properties:
        data:
          type: object
        message:
          type: string
    responseObjectArr:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
        message:
          type: string

  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "user token"
  responses:
    400:
      description: "error from user"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "wrong input"
    404:
      description: "data not found"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "account not registered"
    500:
      description: "error from server"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: "server problem"
