// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	class "dashboardq-be/features/class"

	mock "github.com/stretchr/testify/mock"
)

// ClassData is an autogenerated mock type for the ClassData type
type ClassData struct {
	mock.Mock
}

// Create provides a mock function with given fields: userID, newClass
func (_m *ClassData) Create(userID uint, newClass class.Core) (class.Core, error) {
	ret := _m.Called(userID, newClass)

	var r0 class.Core
	if rf, ok := ret.Get(0).(func(uint, class.Core) class.Core); ok {
		r0 = rf(userID, newClass)
	} else {
		r0 = ret.Get(0).(class.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, class.Core) error); ok {
		r1 = rf(userID, newClass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: userID, classID
func (_m *ClassData) Delete(userID uint, classID uint) error {
	ret := _m.Called(userID, classID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, classID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Show provides a mock function with given fields: classID
func (_m *ClassData) Show(classID uint) (class.Core, error) {
	ret := _m.Called(classID)

	var r0 class.Core
	if rf, ok := ret.Get(0).(func(uint) class.Core); ok {
		r0 = rf(classID)
	} else {
		r0 = ret.Get(0).(class.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShowAll provides a mock function with given fields:
func (_m *ClassData) ShowAll() ([]class.Core, error) {
	ret := _m.Called()

	var r0 []class.Core
	if rf, ok := ret.Get(0).(func() []class.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]class.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userID, classID, newUpdate
func (_m *ClassData) Update(userID uint, classID uint, newUpdate class.Core) (class.Core, error) {
	ret := _m.Called(userID, classID, newUpdate)

	var r0 class.Core
	if rf, ok := ret.Get(0).(func(uint, uint, class.Core) class.Core); ok {
		r0 = rf(userID, classID, newUpdate)
	} else {
		r0 = ret.Get(0).(class.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint, class.Core) error); ok {
		r1 = rf(userID, classID, newUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClassData interface {
	mock.TestingT
	Cleanup(func())
}

// NewClassData creates a new instance of ClassData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClassData(t mockConstructorTestingTNewClassData) *ClassData {
	mock := &ClassData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
