// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	mentee "dashboardq-be/features/mentee"

	mock "github.com/stretchr/testify/mock"
)

// MenteeService is an autogenerated mock type for the MenteeService type
type MenteeService struct {
	mock.Mock
}

// AddMentee provides a mock function with given fields: token, newMentee
func (_m *MenteeService) AddMentee(token interface{}, newMentee mentee.Core) (mentee.Core, error) {
	ret := _m.Called(token, newMentee)

	var r0 mentee.Core
	if rf, ok := ret.Get(0).(func(interface{}, mentee.Core) mentee.Core); ok {
		r0 = rf(token, newMentee)
	} else {
		r0 = ret.Get(0).(mentee.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, mentee.Core) error); ok {
		r1 = rf(token, newMentee)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShowAll provides a mock function with given fields:
func (_m *MenteeService) ShowAll() ([]mentee.Core, error) {
	ret := _m.Called()

	var r0 []mentee.Core
	if rf, ok := ret.Get(0).(func() []mentee.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mentee.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMenteeService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMenteeService creates a new instance of MenteeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMenteeService(t mockConstructorTestingTNewMenteeService) *MenteeService {
	mock := &MenteeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
